### ISSUE TITLE
Possible bug in `C4SubgroupsSpecialLinearGroupGeneric`

### ISSUE THREAD

**Issue by fingolfin** [ssiccha/ClassicalMaximals#11]
It says:
```gap
    if q = 2 and 2 in divisorListOfn then
        Remove(divisorListOfn, 2);
    fi;
```
But this removes the element at *position* 2 from the list, whatever that may be. I suspect you really meant `RemoveSet(divisorListOfn, 2);`?

**Comment by maxhauck** [comment]
Good catch!
